version: "2"
services:
    chaplin_node:
        build: node
        volumes:
            - ../..:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_php:
        build: php
        volumes:
            - ../..:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_convert:
        build: listener/convert
        volumes:
            - ../..:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_youtube:
        build: listener/youtube
        volumes:
            - ../..:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_vimeo:
        build: listener/vimeo
        volumes:
            - ../..:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_email:
        build: listener/email
        volumes:
            - ../..:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    nginx:
        image: nginx
    redis:
        image: redis
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: testtest123
            MYSQL_DATABASE: chaplin
            MYSQL_USER: chaplin
            MYSQL_PASSWORD: chaplin
    rabbitmq:
        image: rabbitmq
