version: "3"
services:
    chaplin_node:
        build:
            context: ../..
            dockerfile: servers/docker/node/Dockerfile
        image: chaplin-node
    chaplin_api:
        build:
            context: ../..
            dockerfile: servers/docker/php/api/Dockerfile
        image: chaplin-php-api
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_cli_convert:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/convert/Dockerfile
        image: chaplin-php
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_cli_youtube:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/youtube/Dockerfile
        image: chaplin-php
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_cli_vimeo:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/vimeo/Dockerfile
        image: chaplin-php
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_cli_email:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/email/Dockerfile
        image: chaplin-php
        depends_on:
            - redis
            - mysql
            - rabbitmq
    nginx:
        image: nginx
        links:
            - chaplin_node:node
            - chaplin_api:api
        depends_on:
            - chaplin_node
            - chaplin_api
        ports:
            - "80:80"
    redis:
        image: redis
    mysql:
        image: mysql
    rabbitmq:
        image: rabbitmq
