version: "2"
services:
    chaplin_node:
        image: node
        volumes:
            - ../../src/js:/var/www
        command: npm start
    chaplin_php:
        image: php:fpm
        volumes:
            - ../../src/php:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_convert:
        image: php
        volumes:
            - ../../src/php:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
        command: php -a
    chaplin_listener_youtube:
        image: php
        volumes:
            - ../../src/php:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
        command: php -a
    chaplin_listener_vimeo:
        image: php
        volumes:
            - ../../src/php:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
        command: php -a
    chaplin_listener_email:
        image: php
        volumes:
            - ../../src/php:/var/www
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
        command: php -a
    nginx:
        image: nginx
        links:
            - node:chaplin_node
            - php:chaplin_php
        volumes:
            - ../../src/php:/var/www
    redis:
        image: redis
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: testtest123
            MYSQL_DATABASE: chaplin
            MYSQL_USER: chaplin
            MYSQL_PASSWORD: chaplin
    rabbitmq:
        image: rabbitmq
