version: "3"
services:
    node:
        environment:
            - NODE_ENV=${NODE_ENV}
        build:
            context: ../..
            dockerfile: servers/docker/node/Dockerfile
        volumes:
            - ../../src/js:/app
        depends_on:
            - redis
            - mysql
            - rabbitmq
    api:
        build:
            context: ../..
            dockerfile: servers/docker/php/api/Dockerfile
        environment:
            - APPLICATION_ENV=${APPLICATION_ENV}
            - SQL_ADAPTER=${SQL_ADAPTER}
            - SQL_PASSWORD=${SQL_PASSWORD}
            - SQL_USER=${SQL_USER}
            - SQL_DATABASE=${SQL_DATABASE}
            - SQL_HOST=${SQL_HOST}
            - SQL_PORT=${SQL_PORT}
            - AMQP_HOST=${AMQP_HOST}
            - AMQP_PORT=${AMQP_PORT}
            - AMQP_USER=${AMQP_USER}
            - AMQP_PASSWORD=${AMQP_PASSWORD}
            - AMQP_VHOST=${AMQP_VHOST}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_USE_TLS=${SMTP_USE_TLS}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
            - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
            - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
            - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
        volumes:
            - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_convert:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/convert/Dockerfile
        environment:
            - APPLICATION_ENV=${APPLICATION_ENV}
            - SQL_ADAPTER=${SQL_ADAPTER}
            - SQL_PASSWORD=${SQL_PASSWORD}
            - SQL_USER=${SQL_USER}
            - SQL_DATABASE=${SQL_DATABASE}
            - SQL_HOST=${SQL_HOST}
            - SQL_PORT=${SQL_PORT}
            - AMQP_HOST=${AMQP_HOST}
            - AMQP_PORT=${AMQP_PORT}
            - AMQP_USER=${AMQP_USER}
            - AMQP_PASSWORD=${AMQP_PASSWORD}
            - AMQP_VHOST=${AMQP_VHOST}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_USE_TLS=${SMTP_USE_TLS}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        volumes:
            - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_youtube:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/youtube/Dockerfile
        environment:
            - APPLICATION_ENV=${APPLICATION_ENV}
            - SQL_ADAPTER=${SQL_ADAPTER}
            - SQL_PASSWORD=${SQL_PASSWORD}
            - SQL_USER=${SQL_USER}
            - SQL_DATABASE=${SQL_DATABASE}
            - SQL_HOST=${SQL_HOST}
            - SQL_PORT=${SQL_PORT}
            - AMQP_HOST=${AMQP_HOST}
            - AMQP_PORT=${AMQP_PORT}
            - AMQP_USER=${AMQP_USER}
            - AMQP_PASSWORD=${AMQP_PASSWORD}
            - AMQP_VHOST=${AMQP_VHOST}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_USE_TLS=${SMTP_USE_TLS}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - YOUTUBE_API_TOKEN=${YOUTUBE_API_TOKEN}
        volumes:
            - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_vimeo:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/vimeo/Dockerfile
        environment:
            - APPLICATION_ENV=${APPLICATION_ENV}
            - SQL_ADAPTER=${SQL_ADAPTER}
            - SQL_PASSWORD=${SQL_PASSWORD}
            - SQL_USER=${SQL_USER}
            - SQL_DATABASE=${SQL_DATABASE}
            - SQL_HOST=${SQL_HOST}
            - SQL_PORT=${SQL_PORT}
            - AMQP_HOST=${AMQP_HOST}
            - AMQP_PORT=${AMQP_PORT}
            - AMQP_USER=${AMQP_USER}
            - AMQP_PASSWORD=${AMQP_PASSWORD}
            - AMQP_VHOST=${AMQP_VHOST}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_USE_TLS=${SMTP_USE_TLS}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - VIMEO_CLIENTSECRET=${VIMEO_CLIENTSECRET}
            - VIMEO_CLIENTID=${VIMEO_CLIENTID}
            - VIMEO_ACCESSTOKEN=${VIMEO_ACCESSTOKEN}
        volumes:
            - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_email:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/email/Dockerfile
        environment:
            - APPLICATION_ENV=${APPLICATION_ENV}
            - SQL_ADAPTER=${SQL_ADAPTER}
            - SQL_PASSWORD=${SQL_PASSWORD}
            - SQL_USER=${SQL_USER}
            - SQL_DATABASE=${SQL_DATABASE}
            - SQL_HOST=${SQL_HOST}
            - SQL_PORT=${SQL_PORT}
            - AMQP_HOST=${AMQP_HOST}
            - AMQP_PORT=${AMQP_PORT}
            - AMQP_USER=${AMQP_USER}
            - AMQP_PASSWORD=${AMQP_PASSWORD}
            - AMQP_VHOST=${AMQP_VHOST}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_USE_TLS=${SMTP_USE_TLS}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        volumes:
            - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    nginx:
        build:
            context: ../..
            dockerfile: servers/docker/nginx/Dockerfile
        environment:
            - APPLICATION_ENV=${APPLICATION_ENV}
            - VHOST=${VHOST}
            - VHOST_PORT=${VHOST_PORT}
            - VHOST_SHORT=${VHOST_SHORT}
            - VHOST_NODE=${VHOST_NODE}
            - VHOST_NODE_PORT=${VHOST_NODE_PORT}
            - VHOST_GUI=${VHOST_GUI}
            - API_HOST=${API_HOST}
            - API_PORT=${API_PORT}
            - NODE_HOST=${NODE_HOST}
            - NODE_PORT=${NODE_PORT}
        volumes:
            - ../../src/php:/var/www
        depends_on:
            - node
            - api
        ports:
            - 80:80
    redis:
        image: redis
    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
            - MYSQL_DATABASE=${SQL_DATABASE}
            - MYSQL_USER=${SQL_USER}
            - MYSQL_PASSWORD=${SQL_PASSWORD}
        image: mysql
    rabbitmq:
        environment:
            - AMQP_HOST=${AMQP_HOST}
            - AMQP_PORT=${AMQP_PORT}
            - AMQP_USER=${AMQP_USER}
            - AMQP_PASSWORD=${AMQP_PASSWORD}
            - AMQP_VHOST=${AMQP_VHOST}
        image: rabbitmq
