version: "3"
services:
    chaplin_node:
        build:
            context: ../..
            dockerfile: servers/docker/node/Dockerfile
        image: chaplin-node
    chaplin_php:
        build:
            context: ../..
            dockerfile: servers/docker/php/api/Dockerfile
        image: chaplin-php-api
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_convert:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/convert/Dockerfile
        image: chaplin-php
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_youtube:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/youtube/Dockerfile
        image: chaplin-php
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_vimeo:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/vimeo/Dockerfile
        image: chaplin-php
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    chaplin_listener_email:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/email/Dockerfile
        image: chaplin-php
        links:
            - redis:redis
            - mysql:mysql
            - rabbitmq:rabbitmq
        depends_on:
            - redis
            - mysql
            - rabbitmq
    nginx:
        image: nginx
        links:
            - chaplin_node:node
            - chaplin_php:php
        depends_on:
            - chaplin_node
            - chaplin_php
        ports:
            - "80:80"
    redis:
        image: redis
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: testtest123
            MYSQL_DATABASE: chaplin
            MYSQL_USER: chaplin
            MYSQL_PASSWORD: chaplin
    rabbitmq:
        image: rabbitmq
