version: "3"
services:
    node:
        build:
            context: ../..
            dockerfile: servers/docker/node/Dockerfile
        #volumes:
        #    - ../../src/js:/app
        depends_on:
            - redis
            - mysql
            - rabbitmq
    api:
        build:
            context: ../..
            dockerfile: servers/docker/php/api/Dockerfile
        #volumes:
        #    - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_convert:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/convert/Dockerfile
        #volumes:
        #    - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_youtube:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/youtube/Dockerfile
        #volumes:
        #    - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_vimeo:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/vimeo/Dockerfile
        #volumes:
        #    - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    cli_email:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/email/Dockerfile
        #volumes:
        #    - ../../src/php:/var/www
        depends_on:
            - redis
            - mysql
            - rabbitmq
    nginx:
        build:
            context: ../..
            dockerfile: servers/docker/nginx/Dockerfile
        #volumes:
        #    - ../../src/php:/var/www
        depends_on:
            - api
    redis:
        image: redis
    mysql:
        image: mysql
    rabbitmq:
        image: rabbitmq
